name: Build RSDKv5

on: workflow_dispatch

# each artifact is like 15MB so we'll start by only doing it manually
# on:
#   push:
#     branches:
#       - master

# TODO: readd with: submodules: recursive once we can

jobs:
  v5-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libsdl2-dev libtheora-dev libglew-dev libglfw3-dev
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH # add vitasdk tool to $PATH
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh
          cd ..
      - name: Build RSDKv5 + U VITA
        run: |
          cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-linux
          path: bin/Linux
